// foodDB_freschi.js — da cataloghi Selecta + MARR (693 prodotti)
export const FRESCHI_DB = [

  // ──────────────────────────────────────────────────
  // ALTRI FRESCHI
  // ──────────────────────────────────────────────────
  { keywords: ["controfiletto di cervo allevato nuova zelanda (gelo)", "controfiletto cervo allevato nuova zelanda (gelo)"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["spalla disossata di cervo allevato nuova zelanda", "spalla disossata cervo allevato nuova zelanda"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["masago wasabi uova di capelin", "masago wasabi uova capelin"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["masago soja uova di capelin", "masago soja uova capelin"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["uova di coregone", "uova coregone"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["uova di luccio", "uova luccio"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["uova di trota iridea salmonata", "uova trota iridea salmonata"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["uova di salmerino", "uova salmerino"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["uova di salmone", "uova salmone"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["sardina in olio extra vergine di oliva prunier", "sardina olio extra vergine oliva prunier"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["115 g 11,50 cad. 1"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["sardina in olio extra vergine di oliva piccante prunier", "sardina olio extra vergine oliva piccante prunier"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["storione in olio extra vergine di oliva al limone prunier", "storione olio extra vergine oliva limone prunier"], sotto1: "Altri Freschi", sotto2: "" },
  { keywords: ["storione al vino bianco e aromi prunier", "storione vino bianco aromi prunier"], sotto1: "Altri Freschi", sotto2: "" },

  // ──────────────────────────────────────────────────
  // FORMAGGI NOBILI
  // ──────────────────────────────────────────────────
  { keywords: ["2045 toma dalta quota - valle daosta - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["2045 toma dalta quota - valle daosta - forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["1 kg ca. spicchio s/v 49,00 al kg. 4%", "1 kg ca. spicchio s/v 49,00 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["8 kg forma intera 49,00 al kg. 4%", "8 kg forma intera 49,00 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["6 kg forma intera 18,40 al kg. 4%", "6 kg forma intera 18,40 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bagoss di bagolino - lombardia - forma intera", "bagoss bagolino - lombardia - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bianco sottobosco al tartufo - piemonte", "bianco sottobosco tartufo - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blu di morozzo - piemonte", "blu morozzo - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bra duro dop - piemonte - spicchio la bruna", "bra duro dop - piemonte - spicchio bruna"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciocavallo podolico - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cacioricotta affumicata bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cacioricotta vaccina bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cocciuto in terra cruda - campania", "cocciuto terra cruda - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["intera (disponibile solo a esaurimento fontina", "intera (disponibile solo esaurimento fontina"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fontina dalpeggio dop - valle daosta - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["6 kg 1/2 forma - ruota 12,50 al kg. 4%", "6 kg 1/2 forma - ruota 12,50 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["6 kg scatola nera con 14,40 al kg. 4%", "6 kg scatola nera 14,40 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorgonzola dolce dop - piemonte - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["12 kg forma intera 14,20 al kg. 4%", "12 kg forma intera 14,20 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["900 g spicchio s/v 23,30 al kg. 4%", "900 g spicchio s/v 23,30 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["7 kg forma intera 23,30 al kg. 4%", "7 kg forma intera 23,30 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["nero del montale - lombardia", "nero montale - lombardia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["oro nero - emilia romagna - mezza forma ruota"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["oro nero - emilia romagna - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["1 kg forma intera s/v 18,70 al kg. 4%", "1 kg forma intera s/v 18,70 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provola delle madonie - sicilia", "provola madonie - sicilia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["1 kg forma intera 20,20 al kg. 4%", "1 kg forma intera 20,20 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provola piccador bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provolone del monaco dop - campania", "provolone monaco dop - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["5 kg forma intera 26,60 al kg. 4%", "5 kg forma intera 26,60 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["5 kg spicchio s/v 12,40 al kg. 4%", "5 kg spicchio s/v 12,40 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["20 kg forma intera 12,10 al kg. 4%", "20 kg forma intera 12,10 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ragusano dop - sicilia - trancio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ragusano dop - sicilia - mezza forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ragusano dop - sicilia - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["7 kg forma intera 17,30 al kg. 4%", "7 kg forma intera 17,30 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ricotta affumicata stagionata - friuli-venezia giulia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["roccolino al tartufo", "roccolino tartufo"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["rubbia valtaleggio - lombardia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["scamorza affumicata bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["schiena dasino giovane - campania - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["sora stagionata - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["taleggio dop - lombardia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["testun al barolo - piemonte", "testun barolo - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma piemontese dop - piemonte - la bruna", "toma piemontese dop - piemonte - bruna"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma piemontese dop - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomini da griglia - piemonte", "tomini griglia - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomini freschi - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomino a rotolo", "tomino rotolo"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tibert - piemonte - la bruna", "tibert - piemonte - bruna"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tuma persa - sicilia - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ubriaco al raboso - veneto - forma intera", "ubriaco raboso - veneto - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["valtellina casera dop - lombardia - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["vezzena dalpeggio - trentino - mezza forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["vezzena dalpeggio - trentino - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["vezzena dolce - trentino - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blu di capra al cucchiaio", "blu capra cucchiaio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blu di capra - lombardia - forma intera", "blu capra - lombardia - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bouchon - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bouchon aromatizzati - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["250 g forma intera 29,90 al kg. 4%", "250 g forma intera 29,90 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caprino al pepe nero bio - puglia - querceta", "caprino pepe nero bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["300 g forma intera s/v 31,60 al kg. 4%", "300 g forma intera s/v 31,60 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["300 g forma intera s/v 29,90 al kg. 4%", "300 g forma intera s/v 29,90 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["300 g forma intera s/v 27,80 al kg. 4%", "300 g forma intera s/v 27,80 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["robiola in foglie di castagno - piemonte", "robiola foglie castagno - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["robiola in cera dapi - piemonte", "robiola cera dapi - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["robiola in foglie di fico - piemonte", "robiola foglie fico - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["500 g forma intera 29,90 al kg. 4%", "500 g forma intera 29,90 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blu di san magno - piemonte - forma intera", "blu san magno - piemonte - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciottina di pecora - campania", "caciottina pecora - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["canestrato pugliese dop - puglia - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gran nuraghe (granglona) - sardegna - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["7 kg 1/2 forma ruota s/v 22,90 al kg. 4%", "7 kg 1/2 forma ruota s/v 22,90 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["7 kg 1/2 forma verticale s/v 22,90 al kg. 4%", "7 kg 1/2 forma verticale s/v 22,90 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gran nuraghe (granglona) - sardegna - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["marzolino - toscana (disponibilità mar-apr)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["marzolino al tartufo - toscana", "marzolino tartufo - toscana"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino dellagro romano - lazio - mezza forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino dellagro romano - lazio - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino romano dop - lazio - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino romano dop - lazio - spicchio 1/8"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino siciliano dop - sicilia - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ricotta al fumo di ginepro bio - abruzzo", "ricotta fumo ginepro bio - abruzzo"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["600 g forma intera s/v 20,30 al kg. 4%", "600 g forma intera s/v 20,30 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blu di bufala - lazio - mezza forma", "blu bufala - lazio - mezza forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blu di bufala - lazio - forma intera", "blu bufala - lazio - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ricotta stagionata misto pecora - sicilia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["1 kg forma intera atm 23,50 al kg. 4%", "1 kg forma intera atm 23,50 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma pagliettina tre latti - piemonte"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano dop grattugiato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano reggiano dop grattugiato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino romano dop grattugiato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["feta dop monoporzione"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["feta dop (preaffettata)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["halloumi"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["banon dop mons (disponibilità feb-ott)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bonde du poitou mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["buche de chèvre mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["buchette del perigord", "buchette perigord"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["buchette de manon bio - mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cabecou"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cabrioles (ex pouligny) mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["carré de saint victor mons (disponibilità mar-set)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["chabichou du poitou dop mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["couffy mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["crottin de chavignol dop mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["crottin cendré mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["120 g forma intera 9,90 cad. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["galette de l’oisellière mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["le barriquet mons", "barriquet mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["lingot des causses mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mistralou mons (disponibilità mar-set)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["oisellière mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ovalie cendrée mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["petit fiancé"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pico chèvre"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pyramide cendrée auzanne mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["abondance fermier mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["affiné au chablis"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ambré affinato alla birra", "ambré affinato birra"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["beaufort - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bleu cendré mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bleu des neiges petit mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["brie de meaux dop"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["brie de normandie"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["brillat-savarin igp"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["camembert de normandie dop mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["camembert de normandie dop"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["camembert petit"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cantal - spicchio mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cantal jeune - mezza forma ruota"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cantal jeune - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["chaource dop"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["chaource mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["coeur de neufchâtel dop mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["coeur de neufchâtel dop"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +8 mesi - 1/4 forma mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +8 mesi - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +14 mesi - 1/4 di forma mons", "comté +14 mesi - 1/4 forma mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +14 mesi - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +20 mesi - 1/4 forma mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +20 mesi - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +30 mesi - 1/4 forma mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comté +30 mesi - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["comtesse de vichy mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["coulommiers"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["epoisses dop"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["explorateur fleuri"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fondue maison mons (disponibilità set-mar)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fourme dambert mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["langres mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["livarot petit dop"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mimolette"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mimolette extra 18 mesi mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mont dor - vacherin h.d. mons (disponibilità ott-feb)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["munster mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pont leveque dop"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["raclette bio - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["reblochon fermier mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["reblochon di latteria mons", "reblochon latteria mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["reblochon petit mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["soumaintrain petit mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["st. felicien mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["st. marcellin in cocotte mons", "st. marcellin cocotte mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["saint romain - forma intera mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["triple crème"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["triple crème al tartufo estivo", "triple crème tartufo estivo"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["brebis fougere mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["camalou mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fromage du maquis mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["lingot st. nicolas mons (disponibilità mar-ago)"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["roquefort dop j.carles"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma occitana gabietou - mons"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blue shropshire - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blue shropshire - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blue stilton - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blue stilton - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cheddar traditional - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cheddar traditional - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["shropshire al porto e uva di corinto baby - spicchio", "shropshire porto uva corinto baby - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["shropshire al porto e uva di corinto - mezza forma", "shropshire porto uva corinto - mezza forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["shropshire al porto e uva di corinto - forma intera", "shropshire porto uva corinto - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gouda di capra - forma intera", "gouda capra - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gouda di capra - spicchio retail", "gouda capra - spicchio retail"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["reypenaer vsop 24 mesi - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["350 g 12,70 cad. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["reypenaer art collection - delft blue"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["reypenaer vsop 24 mesi - spicchio retail"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["duo reypenaer vsop e gouda di capra", "duo reypenaer vsop gouda capra"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["carrigaline smoked"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["idiazabal dop olmeda origenes"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["la serena torta extremeña olmeda origenes", "serena torta extremeña olmeda origenes"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["230 g spicchio s/v 8,90 cad. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["queso majorero olmeda origenes"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["san simòn da costa olmeda origenes", "san simòn costa olmeda origenes"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["appenzeller extra swisscru - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["baci di berna - swisscru", "baci berna - swisscru"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["emmentaler des grottes 12 mesi swisscru - spicchio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gruyère des grottes"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["32 kg forma intera 34,20 al kg. 4%", "32 kg forma intera 34,20 kg. 4%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["letivaz swisscru - forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tête de moine swisscru"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomme aux fleurs - swisscru"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["burrata tradizionale annodata bio - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["burrata tradizionale - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["burratina bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["burratina - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["burratina bio monoporzione - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mini burratina bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["burratina affumicata bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ciliegine fiordilatte bio - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ciliegine fiordilatte - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["filone pizzeria bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte pizzeria julienne - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte pizzeria cubettato bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte pizzeria cubettato - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte pizzeria bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte pizzeria - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte bio monoporzione - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fiordilatte senza lattosio bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["giuncata primosale bio - puglia querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["giuncatina primosale bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["nodino fiordilatte bio - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["nodino fiordilatte - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["perle di fiordilatte - puglia", "perle fiordilatte - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["raviggiolo - emilia romagna"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["scamorza bianca bio - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["stracciatella bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["stracciatella - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["stracciatella di burrata bio - puglia", "stracciatella burrata bio - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["treccia fiordilatte - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["treccina fiordilatte - puglia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["treccina bio - puglia - querceta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["aversana - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["50 g secchiello da", "50 g secchiello"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["25 g secchiello da", "25 g secchiello"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mozzarella di bufala campana dop - campania", "mozzarella bufala campana dop - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["125 g x 16 secchiello da", "125 g x 16 secchiello"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["125 g 8 bicchieri da", "125 g 8 bicchieri"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["treccione maxi di bufala campana dop - campania", "treccione maxi bufala campana dop - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["zizzona di battipaglia - campania", "zizzona battipaglia - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mozzybag (gelo) - campania"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cream cheese original american elle&vire"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["natural cream cheese"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fromage blanc lissé"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["mascarpone artigianale - emilia romagna"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["robiola di capra spalmabile - lombardia", "robiola capra spalmabile - lombardia"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["filo di acciaio per archetto 12 cm", "filo acciaio archetto 12 cm"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["filo di acciaio per archetto 17 cm", "filo acciaio archetto 17 cm"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["foglie di vite in carta alimentare", "foglie vite carta alimentare"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["stuoie di paglia di segale", "stuoie paglia segale"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciotta caprina botalla"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cheddar fette president"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cheddar fette 176 pz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["cheddar rosso 50%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["foglia finger autunnale 80 pz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.cafffiero ca."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.duro it. orizz."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.duro italiano forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.foglie cast.occelli1/8s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.frutta grappa occel1/4s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.gratt.grandalter 100x5 g"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.gratt.marr busta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.gratt.mix fresco"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.gratt.piemontino valgr1kg"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.gratt.100%it.piemontin1kg"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.lunatico botalla"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.maccagno cervo"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.mix grattugiato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.occelli al barolo", "form.occelli barolo"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.occelli malto/whisk1/8s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.piemontino 16m"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano forma intera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano g.soresin300g"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano gratt."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano gratt.100gmap"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano scaglie"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano orizz."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano 12m"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano 20m"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano gratt.latta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano gratt.5gx200"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano marr 16m"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano stagionato 1/4s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano stagionato 1/8s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["grana padano stagionato 1kgs/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.+d.bruna libro3x250g"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.bertinel30m"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.bertinel36m"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg. mezzano"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.gigantina 36m1/32s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.solodibrun40m1/32s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.vacche ros24m1/32s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.vacche ros24m300gs/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parm.regg.30m montagna 1/32s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg. 24m forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg. 24m 1/4s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg. 24m 1/8s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg. 24m 1kgs/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg.gratt. 5gx100"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg.gratt.busta1kg"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg.marr 24m1/8s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg.marr 24m1kgs/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg.scaglie"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano regg.24m metaorizz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["parmigiano reggiano flow p"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino grattugiato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino rom. deroma 1/8s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino rom. sard.gratt1kg"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino romano sard1/4s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino romano sard300gsv"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["rigato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["selezione beppino occelli 4 pz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tometta erbe arom.botalla"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tometta peperoncino botalla"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bel paese forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["blu di grotta botalla100%capra", "blu grotta botalla100%capra"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bra tenero forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["bra tenero"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciocavallo fiaschetto"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciocavallo silano delizi"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciocavallo stag.grotta deliz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["castelmagno alpeggio1/4s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["castelmagno"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["dolcetto gorg/mascar.1,2kgigor"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["edam fette president"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["edamer"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["edamer ted. fette"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["emmental bavarese fette"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["emmental bavarese trancio2,"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["emmental bavarese"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["emmental francese"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["emmentaler svizzero tranci"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fontina"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.aosta dolce v.g.paradiso"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.bleu daoste v.gran parad"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.castellaccio barrique"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.castelrosso forma rosso"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.foralp"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.kaprone botalla"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.maccagno forma rosso"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.maccagno latte crudo ross"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.maccagno valle elvo botal"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.pecorino diavolett400gs/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.pecorino nocetto"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.pecorino tartufell400gs/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.raclette de saison forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.sbirro botalla"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.valle grande invecchiata"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["galbanino pasta filata"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorg.dolce forma balla"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorg.dolce forma casal"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorgonzola casa leonard1/8"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorgonzola dolce cubet500g"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorgonzola dolce g"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorgonzola gran ris.leo1/2"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorgonzola locatelli"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["gorgonzola piccante"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["italico forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["italico"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["made in pizza prealpi", "made pizza prealpi"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["montasio 60 gg forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino fossa s.caterina"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino pascoli di siena", "pecorino pascoli siena"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino pienza nero stag1,"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino pienza semistagionato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["prep.casearia edameno 45%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provola affumicata latbri"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provolone dolce"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provolone valp. dolce"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provolone valp. dolc100gs/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["provolone valp. picc."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["raschera"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["ricotta pecora stag.pinna"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["roquefort mezza forma 1,3kgca."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["sottilette classiche"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["taleggio arrigoni"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["taleggio"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma piemonte forma rosso"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma piemontese forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma piemontese latte crud"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["toma piemontese"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tuma dla paja occelli"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["valtellina casera forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["alba pecorino tartufo semistag"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["asiago fresco"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["asiago pressato dnt 1/4s/v"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["asiago pressato forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciotta 100%it.arrigoni"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["caciottina toscana busti"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["camembert president 8x31,"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["crutin tartufo occelli"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["feta belas cubetti"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["feta kolios cubetti"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["feta"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fontal alpinella forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fontal alpinella"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["fontal belga bianco forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.botalla ai fiori"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.botalla al pepe colorato", "form.botalla pepe colorato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.botalla alla curcuma", "form.botalla curcuma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.botalla allo zenzero"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.da tavola molle quadro"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.latteria forma"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.latteria fresco daniele"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.monblan c.l.vallee daost"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.pist.bronte busti"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.primo sale"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["form.verzin capra forma2kg"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["maasdamer 45%"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino del busti timbrato", "pecorino busti timbrato"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino delizia sard.lisciasv"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino pepato busti"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["pecorino pist.bronte busti"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["primosale goccia b.100%it1,"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["quartirolo lombardo fresco"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["scamorza affum.castelli"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["scamorza affum.fette bayern1kg"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["scamorza affumicata ca."], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["scamorza bianca castelli"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["scamorza deliziosa bianca"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomette mix botalla 4 pz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomino arrigoni 35gx20pz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomino rotolo 330gx6pz"], sotto1: "Formaggi Nobili", sotto2: "" },
  { keywords: ["tomino 100%it.arrigoni 100gx12"], sotto1: "Formaggi Nobili", sotto2: "" },

  // ──────────────────────────────────────────────────
  // LATTICINI
  // ──────────────────────────────────────────────────
  { keywords: ["burro della normandia naturale - blocco", "burro normandia naturale - blocco"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro della normandia naturale - cestello", "burro normandia naturale - cestello"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro della normandia naturale - panetto", "burro normandia naturale - panetto"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro della normandia demi-sel - blocco", "burro normandia demi-sel - blocco"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro della normandia demi-sel - cestello", "burro normandia demi-sel - cestello"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro della normandia demi-sel - panetto", "burro normandia demi-sel - panetto"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro della bretagna naturale - blocco", "burro bretagna naturale - blocco"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro grandemilia"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro di bufala", "burro bufala"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro naturale charentes-poitou dop echiré"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro demi-sel charentes-poitou dop echiré"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro naturale - rotolo elle&vire"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro demi-sel - rotolo elle&vire"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro demi-sel - rotolo (porzionato) elle&vire"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["burro extra secco 84% in fogli elle&vire", "burro extra secco 84% fogli elle&vire"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["crème fraiche epaisse 42% 2l"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["crème fraiche epaisse 42% 1l"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["crème fraiche epaisse 42% 20 cl"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["panna advantage 15% da cucina elle&amp;vire 1l ct. da", "panna advantage 15% cucina elle&amp;vire 1l ct."], sotto1: "Latticini", sotto2: "" },
  { keywords: ["panna excellence 35% da montare elle&vire 1l ct. da", "panna excellence 35% montare elle&vire 1l ct."], sotto1: "Latticini", sotto2: "" },
  { keywords: ["ricotta bio monoporzione - puglia - querceta"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["ricotta fresca bio - puglia - querceta"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["ricotta mista"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["ricotta di pecora", "ricotta pecora"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["ricotta di pecora da laboratorio - sardegna", "ricotta pecora laboratorio - sardegna"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["1 kg vaschetta 10,00 cad. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["ricottine pugliesi bio - puglia - querceta"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["ricottine pugliesi - puglia"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt vaniglia bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt naturale bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt albicocca bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt castagna bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt fragola bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt frutti di bosco bio mons", "yogurt frutti bosco bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt lampone bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt mirtillo bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt susina bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["yogurt mix bio mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["cubetti di parmigiano reggiano dop - lattina", "cubetti parmigiano reggiano dop - lattina"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["300 g spicchio s/v 29,00 al kg. 4%", "300 g spicchio s/v 29,00 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 24 mesi - spicchio"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 24 mesi - ruota"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["36 kg forma intera 25,50 al kg. 4%", "36 kg forma intera 25,50 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["500 g spicchio s/v 31,10 al kg. 4%", "500 g spicchio s/v 31,10 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["1 kg spicchio s/v 29,30 al kg. 4%", "1 kg spicchio s/v 29,30 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["600 g spicchio s/v 28,95 al kg. 4%", "600 g spicchio s/v 28,95 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["1 kg spicchio s/v 28,95 al kg. 4%", "1 kg spicchio s/v 28,95 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["18 kg 1/2 forma ruota s/v 28,00 al kg. 4%", "18 kg 1/2 forma ruota s/v 28,00 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["36 kg forma intera 26,95 al kg. 4%", "36 kg forma intera 26,95 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["600 g spicchio s/v 30,45 al kg. 4%", "600 g spicchio s/v 30,45 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["1 kg spicchio s/v 30,45 al kg. 4%", "1 kg spicchio s/v 30,45 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["18 kg 1/2 forma ruota s/v 29,45 al kg. 4%", "18 kg 1/2 forma ruota s/v 29,45 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["36 kg forma intera 29,50 al kg. 4%", "36 kg forma intera 29,50 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 36 mesi - spicchio"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 36 mesi - ruota"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["36 kg forma intera 28,90 al kg. 4%", "36 kg forma intera 28,90 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 48 mesi - spicchio"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 48 mesi - spicchio 1/8"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 48 mesi - ruota"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["36 kg forma intera 30,90 al kg. 4%", "36 kg forma intera 30,90 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 60 mesi - spicchio"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["4 kg spicchio 39,20 al kg. 4%", "4 kg spicchio 39,20 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 60 mesi - ruota"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["36 kg forma intera 34,20 al kg. 4%", "36 kg forma intera 34,20 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 72 mesi - spicchio"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["4 kg spicchio 44,50 al kg. 4%", "4 kg spicchio 44,50 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["parmigiano reggiano dop 72 mesi - ruota"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["36 kg forma intera 39,10 al kg. 4%", "36 kg forma intera 39,10 kg. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["grana padano dop - ruota"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["grana padano dop - forma intera"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["grana padano dop senior 20 - ruota"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["grana padano dop senior 20 - forma"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["gli orizzonti del parmigiano reggiano dop", "orizzonti parmigiano reggiano dop"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["2,2 kg s/v in scatola 61,90 a conf. 4%", "2,2 kg s/v scatola 61,90 conf. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["4 kg s/v in scatola 131,00 a conf. 4%", "4 kg s/v scatola 131,00 conf. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["i colori del parmigiano reggiano dop", "colori parmigiano reggiano dop"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["plateau formaggi francesi"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["plateau cadeau 5 pezzi mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["1 kg 44,80 cad. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["plateau centrotavola chèvre mons"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["1 kg cappelliera di legno 49,90 a conf. 4%", "1 kg cappelliera legno 49,90 conf. 4%"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["platò non toccatemi il formaggio (disponibilità gen-ott)", "platò non toccatemi formaggio (disponibilità gen-ott)"], sotto1: "Latticini", sotto2: "" },
  { keywords: ["platò di natale (disponibilità nov-dic)", "platò natale (disponibilità nov-dic)"], sotto1: "Latticini", sotto2: "" },

  // ──────────────────────────────────────────────────
  // SALUMI
  // ──────────────────────────────────────────────────
  { keywords: ["prosciutto crudo castagnolo con osso riserva", "prosciutto crudo castagnolo osso riserva"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto crudo castagnolo senza osso riserva"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto crudo di sauris con osso igp", "prosciutto crudo sauris osso igp"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto crudo di sauris senza osso igp", "prosciutto crudo sauris senza osso igp"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto cotto alta qualità"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coppa di testa", "coppa testa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["mortadella classica presidio slow food"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["mortadella classica (mezza) presidio slow food"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["mortadellina classica presidio slow food"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["pancetta al forno affumicata", "pancetta forno affumicata"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salame rosa presidio slow food"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["spalla cotta grigliata"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["carrè di suino affumicato kaiser-fleish", "carrè suino affumicato kaiser-fleish"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["ciauscolo igp"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["nduja"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salamina da sugo di ferrara", "salamina sugo ferrara"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["soppressata dolce"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["soppressata piccante"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["sopressa veneta senzaglio"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salame di capra affumicato", "salame capra affumicato"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salame annugghjele affumicato di suino nero", "salame annugghjele affumicato suino nero"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["capocollo di martina franca igp", "capocollo martina franca igp"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["guanciale di suino affumicato di sauris", "guanciale suino affumicato sauris"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["lardo di colonnata igp", "lardo colonnata igp"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["concio di lardo di colonnata igp", "concio lardo colonnata igp"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["lardo di montagna", "lardo montagna"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["mocetta di capra", "mocetta capra"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["pagnottella stagionata in crusca", "pagnottella stagionata crusca"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["speck sarner"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["speck di sauris igp", "speck sauris igp"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["speck del trentino", "speck trentino"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["filetto di tacchino affumicato aromatizzato al miele", "filetto tacchino affumicato aromatizzato miele"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["pastrami"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["streaky bacon preaffettato naturale"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salame doca"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["speck di anatra affumicato stagionato", "speck anatra affumicato stagionato"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["90 g 6,80 cad. 10"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["speck di anatra affumicato affettato e ricostituito", "speck anatra affumicato affettato ricostituito"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["bresaola di cervo", "bresaola cervo"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["bresaola di cinghiale", "bresaola cinghiale"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salsiccia di cinghiale", "salsiccia cinghiale"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["lingotto iberico 100%, bellota - pata negra 5j"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["50 g 12 vaschette 14,20 al pz. 10", "50 g 12 vaschette 14,20 pz. 10"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto iberico 100%, bellota busta - pata negra 5j"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["paleta iberico 100%, bellota con osso - pata negra 5j", "paleta iberico 100%, bellota osso - pata negra 5j"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["paleta iberico 100%, bellota senza osso - pata negra 5j"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["lomo stagionato iberico 100%, bellota - pata negra 5j"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["paleta christmas edition 2025 5j"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["paleta iberico bellota senza osso - sigillo rosso casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coppa iberico bellota casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["lomito (presa) iberico bellota casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["guanciale iberico bellota affumicato casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["chorizo iberico bellota casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coppa di testa iberico (cabeza de jabali) casalba", "coppa testa iberico (cabeza de jabali) casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto serralba riserva affumicato casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto serralba riserva casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto serralba riserva senza osso casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosciutto serralba riserva 4 pezzi casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["cecina di vacca intera casalba", "cecina vacca intera casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["cecina di vacca (trancio) casalba", "cecina vacca (trancio) casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["cecina iberica casalba"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["culatello di zibello dop intero podere cadassa", "culatello zibello dop intero podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["80 g 8,20 cad. 1"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["fiocchetto di cantina podere cadassa", "fiocchetto cantina podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["strolghino singolo in astuccio podere cadassa", "strolghino singolo astuccio podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["strolghino podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salame gentile podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["mariola di salame podere cadassa", "mariola salame podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["spalla cotta di san secondo podere cadassa", "spalla cotta san secondo podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["spalla cruda di palasone podere cadassa", "spalla cruda palasone podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coppa pulita pronta per luso podere cadassa", "coppa pulita pronta luso podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coppa intera podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["pancetta arrotolata - intera podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["guanciale stagionato podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["600 g astuccio 11,50 al pz. 10%", "600 g astuccio 11,50 pz. 10%"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["salame cresponetto punto zero podere cadassa"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["1 pz. 9,75 cad. 22%"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.bellota 100% iberico con osso", "prosc.bellota 100% iberico osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.cinta senese con osso", "prosc.cinta senese osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.iberico con osso bernardo sel", "prosc.iberico osso bernardo sel"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.norcia renzini con osso", "prosc.norcia renzini osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma con osso+portaprosciutt", "prosc.parma osso+portaprosciutt"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma dnt 18m con osso", "prosc.parma dnt 18m osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma dnt 24m con osso", "prosc.parma dnt 24m osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma con osso", "prosc.parma osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma veroni con osso", "prosc.parma veroni osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.s.daniele con osso", "prosc.s.daniele osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.s.daniele kings con osso", "prosc.s.daniele kings osso"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coscia suino assisi pepe"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coscia suino sgambato c/pepe"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["coscia suino stag.umbriaco"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["culatello trad.pelato interos/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["culatello tradiz.legato a mano", "culatello tradiz.legato mano"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["culatta di busseto", "culatta busseto"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["culatta mec intera"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["culatta mec"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["fiocco valtellina basic 1/2s/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["fiocco valtellina mottolinis/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.beher unico tagl.colt50g"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.cascinale disossatoaddobbos/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.cascinale disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.crudo affettato cbm"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.crudo disossatostag.lavatos/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.crudo stag.affumicatoc.buo500g"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.cucin.disossatoaddob5,5"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.cucin.disossatoaddob6,+"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.cucin.disossatopress5,5"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.cucin.disossatopress6,+"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.de bellota 100% iberi50g"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.disossatoaddobbo veroni"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.disossatopressato veroni"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.fuoriclasse disossatopres."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.limperatore disossatos/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.la pieve 18m riserva disossato"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.mec disossatomatt.s/g"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.mec disossatopressato"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.naz.disossatoaddobbo 7/8kgs/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.naz.disossatopiatto 7/"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.nazionale bauletto disossato."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.norcia disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.norcia 16m disossatos/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma dnt 18m disossatoadds/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma dnt 18m disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma dnt 24m disossatoadds/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma disossatoaddobbos/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma disossatomatt."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma 16m disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma 18m disossatoadds/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma 18m disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma 30m disossatoadds/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma salum.disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma veroni disossatoaddobbo"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.parma veroni disossatopress."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.s.daniele disossatos/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.sauris disossatoadd. bepi"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.serrano g.reserva diss/v"], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.toscano 20m disossatoadd."], sotto1: "Salumi", sotto2: "" },
  { keywords: ["prosc.val liona kings disossato."], sotto1: "Salumi", sotto2: "" },
]