// ─────────────────────────────────────────────────────────────────────────────
// foodDB_dispensa.js — Database DISPENSA per Ristorai
// Struttura: nome (matching) + testo (varianti) + sotto1/sotto2 + unit
// Fonti: catalogo MARR + catalogo Selecta
// ─────────────────────────────────────────────────────────────────────────────

export const DISPENSA_DB = [
  { keywords: ["pelati"], sotto1: "Conserve", sotto2: "Pomodoro", unit: "kg" },
  { keywords: ["passata pomodoro", "passata di pomodoro", "passata classica"], sotto1: "Conserve", sotto2: "Pomodoro", unit: "kg" },
  { keywords: ["polpa pomodoro", "polpa di pomodoro", "polpa cubetti", "polpa fine"], sotto1: "Conserve", sotto2: "Pomodoro", unit: "kg" },
  { keywords: ["concentrato pomodoro", "doppio concentrato", "triplo concentrato"], sotto1: "Conserve", sotto2: "Pomodoro", unit: "kg" },
  { keywords: ["pomodori secchi", "pomodori essiccati", "pomodori secchi sott'olio"], sotto1: "Conserve", sotto2: "Pomodoro", unit: "kg" },
  { keywords: ["carciofi conserva", "carciofi sott'olio", "carciofi al naturale", "cuori di carciofo"], sotto1: "Conserve", sotto2: "Ortaggi", unit: "kg" },
  { keywords: ["peperoni conserva", "peperoni arrostiti", "peperoni sott'olio", "piquillo"], sotto1: "Conserve", sotto2: "Ortaggi", unit: "kg" },
  { keywords: ["capperi", "capperi in salamoia", "capperi sotto sale", "cucunci"], sotto1: "Conserve", sotto2: "Capperi", unit: "kg" },
  { keywords: ["olive"], sotto1: "Conserve", sotto2: "Olive", unit: "kg" },
  { keywords: ["fagioli conserva", "fagioli in scatola", "fagioli borlotti", "fagioli cannellini"], sotto1: "Conserve", sotto2: "Legumi", unit: "kg" },
  { keywords: ["ceci conserva", "ceci in scatola", "ceci al naturale"], sotto1: "Conserve", sotto2: "Legumi", unit: "kg" },
  { keywords: ["mais conserva", "mais dolce in scatola", "mais al naturale", "ortoriso"], sotto1: "Conserve", sotto2: "Ortaggi", unit: "kg" },
  { keywords: ["tonno conserva", "tonno in scatola", "tonno sott'olio", "tonno al naturale"], sotto1: "Conserve", sotto2: "Pesce", unit: "kg" },
  { keywords: ["acciughe conserva", "alici sott'olio", "acciughe in scatola", "filetti acciughe"], sotto1: "Conserve", sotto2: "Pesce", unit: "kg" },
  { keywords: ["confettura", "marmellata", "confettura di frutta", "composta"], sotto1: "Conserve", sotto2: "Dolci", unit: "kg" },
  { keywords: ["miele"], sotto1: "Conserve", sotto2: "Dolci", unit: "kg" },
  { keywords: ["olio evo", "olio extravergine di oliva"], sotto1: "Condimenti", sotto2: "Olio", unit: "l" },
  { keywords: ["olio oliva", "olio di oliva", "olio vergine"], sotto1: "Condimenti", sotto2: "Olio", unit: "l" },
  { keywords: ["olio semi", "olio di semi", "olio semi vari", "olio girasole", "olio arachidi", "olio soia", "olio mais", "olio palma"], sotto1: "Condimenti", sotto2: "Olio", unit: "l" },
  { keywords: ["olio friggere", "olio per frittura", "frienn"], sotto1: "Condimenti", sotto2: "Olio", unit: "l" },
  { keywords: ["olio nocciola", "olio di nocciola gastronomico"], sotto1: "Condimenti", sotto2: "Olio", unit: "l" },
  { keywords: ["olio sesamo", "olio di sesamo", "sesame oil"], sotto1: "Condimenti", sotto2: "Olio", unit: "l" },
  { keywords: ["olio argan", "olio di argan gastronomico"], sotto1: "Condimenti", sotto2: "Olio", unit: "l" },
  { keywords: ["aceto balsamico", "aceto balsamico di modena igp", "aceto balsamico tradizionale"], sotto1: "Condimenti", sotto2: "Aceto", unit: "l" },
  { keywords: ["aceto vino", "aceto di vino bianco", "aceto di vino rosso", "aceto di mele", "aceto champagne"], sotto1: "Condimenti", sotto2: "Aceto", unit: "l" },
  { keywords: ["salsa di soia", "soy sauce", "shoyu", "tamari", "salsa di soia giapponese"], sotto1: "Condimenti", sotto2: "Salse Etniche", unit: "l" },
  { keywords: ["mirin", "mirin giapponese", "sake da cucina"], sotto1: "Condimenti", sotto2: "Salse Etniche", unit: "l" },
  { keywords: ["ponzu", "ponzu giapponese", "champonzu", "daidai ponzu"], sotto1: "Condimenti", sotto2: "Salse Etniche", unit: "l" },
  { keywords: ["wasabi", "wasabi in pasta", "wasabi in polvere"], sotto1: "Condimenti", sotto2: "Salse Etniche", unit: "kg" },
  { keywords: ["tahini", "pasta di sesamo", "tahina"], sotto1: "Condimenti", sotto2: "Salse Etniche", unit: "kg" },
  { keywords: ["sriracha", "salsa piccante asiatica", "chili sauce"], sotto1: "Condimenti", sotto2: "Salse Etniche", unit: "l" },
  { keywords: ["ketchup", "salsa ketchup", "pomodoro ketchup"], sotto1: "Condimenti", sotto2: "Salse", unit: "l" },
  { keywords: ["maionese"], sotto1: "Condimenti", sotto2: "Salse", unit: "kg" },
  { keywords: ["senape"], sotto1: "Condimenti", sotto2: "Salse", unit: "kg" },
  { keywords: ["mostarda", "mostarda di frutta", "salsa senapata"], sotto1: "Condimenti", sotto2: "Salse", unit: "kg" },
  { keywords: ["salsa worcestershire", "worcester", "salsa inglese"], sotto1: "Condimenti", sotto2: "Salse", unit: "l" },
  { keywords: ["tabasco", "salsa piccante", "hot sauce"], sotto1: "Condimenti", sotto2: "Salse", unit: "l" },
  { keywords: ["tartufo condimento", "crema di tartufo", "salsa tartufata", "condimento al tartufo", "fette di tartufo"], sotto1: "Condimenti", sotto2: "Tartufo", unit: "kg" },
  { keywords: ["pasta"], sotto1: "Secchi", sotto2: "Pasta", unit: "kg" },
  { keywords: ["riso"], sotto1: "Secchi", sotto2: "Riso", unit: "kg" },
  { keywords: ["farina"], sotto1: "Secchi", sotto2: "Farina", unit: "kg" },
  { keywords: ["legumi secchi"], sotto1: "Secchi", sotto2: "Legumi", unit: "kg" },
  { keywords: ["cereali"], sotto1: "Secchi", sotto2: "Cereali", unit: "kg" },
  { keywords: ["zucchero"], sotto1: "Secchi", sotto2: "Zucchero", unit: "kg" },
  { keywords: ["sale"], sotto1: "Secchi", sotto2: "Sale", unit: "kg" },
  { keywords: ["dado", "dado brodo", "brodo granulare", "brodo in polvere"], sotto1: "Secchi", sotto2: "Brodi", unit: "pz" },
  { keywords: ["lievito", "lievito in polvere", "lievito per dolci", "lievito secco", "lievito istantaneo"], sotto1: "Secchi", sotto2: "Lievito", unit: "kg" },
  { keywords: ["amido", "amido di mais", "maizena", "fecola di patate", "frumina"], sotto1: "Secchi", sotto2: "Addensanti", unit: "kg" },
  { keywords: ["pane grattugiato", "pangrattato", "panko", "pane grattato"], sotto1: "Secchi", sotto2: "Panatura", unit: "kg" },
  { keywords: ["spezie"], sotto1: "Secchi", sotto2: "Spezie", unit: "kg" },
  { keywords: ["vaniglia", "baccelli di vaniglia", "estratto di vaniglia", "pasta di vaniglia"], sotto1: "Secchi", sotto2: "Spezie", unit: "kg" },
  { keywords: ["acqua minerale"], sotto1: "Bevande analcoliche", sotto2: "Acqua", unit: "l" },
  { keywords: ["bibite", "bevanda gassata", "soft drink"], sotto1: "Bevande analcoliche", sotto2: "Bibite", unit: "l" },
  { keywords: ["succo frutta", "succo di frutta", "succo polpa", "nettare"], sotto1: "Bevande analcoliche", sotto2: "Succhi", unit: "l" },
  { keywords: ["the", "ice tea", "bevanda al tè"], sotto1: "Bevande analcoliche", sotto2: "Bibite", unit: "l" },
  { keywords: ["sciroppo", "sciroppo bar", "mixyfruit"], sotto1: "Bevande analcoliche", sotto2: "Sciroppi", unit: "l" },
  { keywords: ["bevanda soia", "latte di soia", "bevanda avena", "latte vegetale"], sotto1: "Bevande analcoliche", sotto2: "Bevande Vegetali", unit: "l" },
  { keywords: ["energy drink", "bevanda energetica"], sotto1: "Bevande analcoliche", sotto2: "Bibite", unit: "l" },
  { keywords: ["birra"], sotto1: "Bevande alcoliche", sotto2: "Birra", unit: "l" },
  { keywords: ["vino da cucina", "vino per cucinare", "vino sfuso", "marsala", "vino bianco cucina", "vino rosso cucina"], sotto1: "Bevande alcoliche", sotto2: "Vino", unit: "l" },
  { keywords: ["porto", "vino di porto", "porto ruby", "porto white"], sotto1: "Bevande alcoliche", sotto2: "Vini Liquorosi", unit: "l" },
  { keywords: ["rum"], sotto1: "Superalcolici", sotto2: "Rum", unit: "l" },
  { keywords: ["grappa"], sotto1: "Superalcolici", sotto2: "Grappa", unit: "l" },
  { keywords: ["brandy", "cognac", "armagnac"], sotto1: "Superalcolici", sotto2: "Brandy", unit: "l" },
  { keywords: ["amaro", "liquore amaro", "aperitivo"], sotto1: "Superalcolici", sotto2: "Amaro", unit: "l" },
  { keywords: ["liquore"], sotto1: "Superalcolici", sotto2: "Liquore", unit: "l" },
  { keywords: ["alcool", "alcool puro", "alcool alimentare", "alcool etilico"], sotto1: "Superalcolici", sotto2: "Alcool", unit: "l" },
  { keywords: ["detersivo lavastoviglie", "lavastoviglie liquido", "deterg.lavast", "gel lavastoviglie", "deterg.clorato lavast"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "kg" },
  { keywords: ["disincrostante", "disincrostante lavastoviglie", "detart", "anticalcare lavastoviglie", "jonmatic anticalc"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "l" },
  { keywords: ["brillantante", "brillantante lavastoviglie", "sgocciolatante"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "kg" },
  { keywords: ["sgrassatore", "sgrassatore cucina", "sgrassatore marsiglia", "sgrass cleaner", "deterg.mult.cucina", "pulitutto igieniz", "detergente multiuso cucina", "cif sgrassatore"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "l" },
  { keywords: ["detersivo pavimenti", "deterg.pavim", "nettapavimenti", "floor surface", "xense"], sotto1: "Detersivi", sotto2: "Pulizia Ambienti", unit: "l" },
  { keywords: ["detergente idroalcolico", "det.idroalcol", "alcol igienizzante", "igienizzante superfici", "alo33"], sotto1: "Detersivi", sotto2: "Igiene Ambienti", unit: "l" },
  { keywords: ["candeggina", "candeggiante cloro", "candeggina profumata", "ipoclorito di sodio", "varechina", "cif gel candeggina"], sotto1: "Detersivi", sotto2: "Pulizia Ambienti", unit: "l" },
  { keywords: ["ammorbidente", "ammorbidente bucato"], sotto1: "Detersivi", sotto2: "Bucato", unit: "kg" },
  { keywords: ["anticalcare", "anticalcare bagno", "cif anticalcare", "rimozione calcare"], sotto1: "Detersivi", sotto2: "Pulizia Ambienti", unit: "l" },
  { keywords: ["sapone mani", "sapone liquido mani", "gel igienizzante mani", "saponette hotel"], sotto1: "Detersivi", sotto2: "Igiene Personale", unit: "l" },
  { keywords: ["guanti", "guanti lattice", "guanti nitrile", "guanti vinile"], sotto1: "Detersivi", sotto2: "Igiene Personale", unit: "pz" },
  { keywords: ["spugna", "spugna abrasiva", "spugna acciaio", "spugna cucina", "pannospugna"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "pz" },
  { keywords: ["strofinaccio", "strofinaccio asciugapiatti", "strofinaccio scozia", "canovaccio"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "pz" },
  { keywords: ["carta igienica", "carta ig", "rotoli carta igienica", "carta interfoliata", "jumbo", "mini jumbo", "carta igienica everyday"], sotto1: "Detersivi", sotto2: "Carta", unit: "pz" },
  { keywords: ["tovaglia", "tovaglietta carta", "tovagliolo carta", "tovaglia rotolo"], sotto1: "Detersivi", sotto2: "Carta", unit: "pz" },
  { keywords: ["pellicola", "pellicola trasparente", "pellicola pvc", "film alimentare", "pellicola microonde"], sotto1: "Detersivi", sotto2: "Imballaggi", unit: "pz" },
  { keywords: ["sacchi immondizia", "sacchi neri", "sacchi biodegradabili", "sacchi azzurri", "sacchi gialli", "sacchi neutri"], sotto1: "Detersivi", sotto2: "Imballaggi", unit: "pz" },
  { keywords: ["carta forno", "carta da forno", "carta antiaderente", "cartaforno"], sotto1: "Detersivi", sotto2: "Imballaggi", unit: "pz" },
  { keywords: ["carta alluminio", "carta stagnola", "foglio alluminio", "alluminio alimentare"], sotto1: "Detersivi", sotto2: "Imballaggi", unit: "pz" },
  { keywords: ["deodorante ambiente", "deodorante", "deodoforante", "profumatore ambiente", "air freshener", "deofor", "deodorante wc", "deodorante cucina", "deodorante pavimenti"], sotto1: "Detersivi", sotto2: "Igiene Ambienti", unit: "pz" },
  { keywords: ["detergente wc", "detergente bagno", "gel wc", "anticalcare wc", "ducale wc", "net wc"], sotto1: "Detersivi", sotto2: "Pulizia Ambienti", unit: "l" },
  { keywords: ["detergente inox", "lucido inox", "lucidante acciaio inox", "pulitore inox", "nettainox"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "l" },
  { keywords: ["caustica", "soda caustica", "detergente caustificante", "decapante forni", "pulisci forno caustico", "detergente alcalino forno", "rational"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "kg" },
  { keywords: ["detergente forno", "pulisci forno", "detergente forni", "desgrassante forno", "rational tabs", "rational liquido"], sotto1: "Detersivi", sotto2: "Pulizia Cucina", unit: "pz" },
  { keywords: ["lucido superfici", "lucido multiuso", "lucidante superfici", "cera pavimenti"], sotto1: "Detersivi", sotto2: "Pulizia Ambienti", unit: "l" },
  { keywords: ["secchio", "secchio pulizie", "secchio con strizzatore", "secchio plastica"], sotto1: "Detersivi", sotto2: "Attrezzature", unit: "pz" },
  { keywords: ["mocio", "mop", "mocio lavapavimenti", "frange mocio", "ricambio mocio"], sotto1: "Detersivi", sotto2: "Attrezzature", unit: "pz" },
  { keywords: ["scopa", "spazzolone", "granata", "spazzolone pavimenti"], sotto1: "Detersivi", sotto2: "Attrezzature", unit: "pz" },
  { keywords: ["carta asciugamani", "carta mani", "asciugamani carta", "carta interfogliata", "carta rotolo", "carta bobina"], sotto1: "Detersivi", sotto2: "Carta", unit: "pz" },

  // ── Frutta Secca ─────────────────────────────────────────────────────────
  { keywords: ["nocciole", "nocciola", "nocciole pelate", "nocciole tostate", "nocciole pelate tostate", "granella nocciole", "hazelnut"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  { keywords: ["mandorle", "mandorla", "mandorle pelate", "mandorle tostate", "granella mandorle", "almond"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  { keywords: ["pistacchi", "pistacchio", "granella pistacchio", "granella pistacchio 2/4", "pistacchi pelati", "pistachio"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  { keywords: ["pinoli", "pinolo", "pine nut"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  { keywords: ["noci", "noce", "noci sgusciate", "walnut"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  { keywords: ["uvetta", "uvetta sultanina", "uva passa", "raisin"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  // ── Legumi Secchi ─────────────────────────────────────────────────────────
  { keywords: ["ceci secchi", "ceci", "ceci melandri", "chickpeas", "garbanzo"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  { keywords: ["lenticchie", "lenticchia", "lentils"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  { keywords: ["fagioli secchi", "cannellini secchi", "fagioli borlotti secchi"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  // ── Dolci Secchi ─────────────────────────────────────────────────────────
  { keywords: ["amaretti", "amaretto", "amaretti bonomi", "amaretti lazzaroni", "biscotto amaretto"], sotto1: "Secchi", sotto2: "", unit: "pz" },
  { keywords: ["savoiardi", "savoiardo", "lady finger", "vicenzi savoiardi"], sotto1: "Secchi", sotto2: "", unit: "pz" },
  { keywords: ["cantucci", "cantuccini", "biscotti toscani"], sotto1: "Secchi", sotto2: "", unit: "pz" },
  { keywords: ["cioccolato fondente", "fondente 70", "fondente 55", "dark chocolate"], sotto1: "Secchi", sotto2: "", unit: "kg" },
  // ── Conserve Vegetali ─────────────────────────────────────────────────────
  { keywords: ["capperi sottaceto", "capperi", "cappero", "frutti cappero", "frutti capperi", "frutti cappero aceto", "caper"], sotto1: "Conserve", sotto2: "", unit: "kg" },
  { keywords: ["peperoni arrostiti", "peperoni grigliati", "peperoni arr nat", "peperoni rossi arrosto"], sotto1: "Conserve", sotto2: "", unit: "kg" },
]
