// foodDB_carni.js — da cataloghi Selecta + MARR (669 prodotti)
export const CARNI_DB = [

  // ──────────────────────────────────────────────────
  // AGNELLO
  // ──────────────────────────────────────────────────
  { keywords: ["spalla taglio rotondo di agnello irlanda", "spalla taglio rotondo agnello irlanda"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["cosciotto di agnello irlanda", "cosciotto agnello irlanda"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["stinco posteriore di agnello irlanda", "stinco posteriore agnello irlanda"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["controfiletto senza copertina di agnello galles igp", "controfiletto senza copertina agnello galles igp"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["spalla con osso (taglio tondo) di agnello galles igp", "spalla osso (taglio tondo) agnello galles igp"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["pancia senz'osso di agnello galles igp", "pancia senz'osso agnello galles igp"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["agnello da latte nostrano senza testa e senza corata", "agnello latte nostrano senza testa senza corata"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["agnello da latte intero", "agnello latte intero"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["capretto da latte senza testa francia", "capretto latte senza testa francia"], sotto1: "Agnello", sotto2: "" },
  { keywords: ["capretto da latte intero con testa nazionale", "capretto latte intero testa nazionale"], sotto1: "Agnello", sotto2: "" },

  // ──────────────────────────────────────────────────
  // ANATRA
  // ──────────────────────────────────────────────────
  { keywords: ["anatra maschio a busto nazionale", "anatra maschio busto nazionale"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["anatra femmina a busto nazionale", "anatra femmina busto nazionale"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["canette de barberie a busto francia", "canette de barberie busto francia"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["petto di anatra canette francia", "petto anatra canette francia"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["petto di anatra maschio nazionale", "petto anatra maschio nazionale"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["petto di anatra femmina nazionale", "petto anatra femmina nazionale"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["petto di anatra canette de barberie francia", "petto anatra canette de barberie francia"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["petto di anatra grassa (taglio magret) ungheria", "petto anatra grassa (taglio magret) ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["petto di anatra mulard (taglio magret)", "petto anatra mulard (taglio magret)"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["coscia di anatra mulard francia", "coscia anatra mulard francia"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["coscia di anatra maschio nazionale", "coscia anatra maschio nazionale"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["fegatelli di anatra naturali", "fegatelli anatra naturali"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["fegato grasso di anatra mulard 1° qualità", "fegato grasso anatra mulard 1° qualità"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["fegato grasso d'anatra extra"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["fegato grasso di oca qualità extra ungheria", "fegato grasso oca qualità extra ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["fegato grasso di oca selezione per terrine ungheria", "fegato grasso oca selezione terrine ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["oca a busto ungheria", "oca busto ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["oca di tolosa semidisossata (taglio paletot) ungheria", "oca tolosa semidisossata (taglio paletot) ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["petto di oca (taglio magret) ungheria", "petto oca (taglio magret) ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["coscia di oca (taglio per confit) ungheria", "coscia oca (taglio confit) ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["coscia di oca disossata ungheria", "coscia oca disossata ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["durelli di oca ungheria", "durelli oca ungheria"], sotto1: "Anatra", sotto2: "" },
  { keywords: ["collo di oca pelle ungheria", "collo oca pelle ungheria"], sotto1: "Anatra", sotto2: "" },

  // ──────────────────────────────────────────────────
  // BOVINO
  // ──────────────────────────────────────────────────
  { keywords: ["lombo 8 coste (con testa del filetto) di vacca irlanda", "lombo 8 coste (con testa filetto) vacca irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo 8 coste (senza filetto) di vaca loura vicentico", "lombo 8 coste (senza filetto) vaca loura vicentico"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo 8 coste (con testa del filetto) di bovino polonia", "lombo 8 coste (con testa filetto) bovino polonia"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["tomahawk 5 coste di bovino irlanda", "tomahawk 5 coste bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["t-bone 0 coste di bovino irlanda", "t-bone 0 coste bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino irlanda", "controfiletto bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["testa di filetto di bovino irlanda", "testa filetto bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["costine della costata di bovino irlanda", "costine costata bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone pad di bovino irlanda", "scamone pad bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["codone (picanha) di bovino irlanda", "codone (picanha) bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa vero binden di bovino irlanda", "fesa vero binden bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello di bovino irlanda", "girello bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce di bovino irlanda", "noce bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["spinacino di bovino irlanda", "spinacino bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["diaframma di bovino irlanda", "diaframma bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["guanciale di bovino irlanda", "guanciale bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["coda di bovino irlanda", "coda bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["muscolo di bovino irlanda", "muscolo bovino irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) di bovino black angus irlanda", "cuore costata (rib eye) bovino black angus irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto a metà di bovino black angus irlanda", "controfiletto metà bovino black angus irlanda"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bovino scozia aberdeen angus caledonia crown"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) di bovino scozia", "cuore costata (rib eye) bovino scozia"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto di bovino wagyu a5 japan - kagoshima", "filetto bovino wagyu a5 japan - kagoshima"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino wagyu a5 japan - kagoshima", "controfiletto bovino wagyu a5 japan - kagoshima"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["entrecote di bovino wagyu a3/a4 japan - kagoshima", "entrecote bovino wagyu a3/a4 japan - kagoshima"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino wagyu a3/a4 japan - kagoshima", "controfiletto bovino wagyu a3/a4 japan - kagoshima"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto di bovino wagyu a5 japan - hokkaido", "filetto bovino wagyu a5 japan - hokkaido"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["entrecote di bovino wagyu a5 japan - hokkaido", "entrecote bovino wagyu a5 japan - hokkaido"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino wagyu a5 japan - hokkaido", "controfiletto bovino wagyu a5 japan - hokkaido"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto di bovino wagyu a4 japan - hokkaido", "filetto bovino wagyu a4 japan - hokkaido"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["entrecote di bovino wagyu a4 japan - hokkaido", "entrecote bovino wagyu a4 japan - hokkaido"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino wagyu a4 japan - hokkaido", "controfiletto bovino wagyu a4 japan - hokkaido"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["tomahawk 7 coste di bovino wagyu spagna", "tomahawk 7 coste bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) di bovino wagyu spagna", "cuore costata (rib eye) bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto di bovino wagyu spagna", "filetto bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone a cuore di bovino wagyu spagna", "scamone cuore bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["codone (picanha) di bovino wagyu spagna", "codone (picanha) bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["ala di bovino wagyu spagna", "ala bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fianchetto (flank steak) di bovino wagyu spagna", "fianchetto (flank steak) bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) la piemontese", "cuore costata (rib eye) piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto la piemontese", "controfiletto piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto con cordone la piemontese", "filetto cordone piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone a cuore la piemontese", "scamone cuore piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce la piemontese", "noce piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["reale la piemontese", "reale piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["punta di petto senza osso la piemontese", "punta petto senza osso piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["diaframma la piemontese", "diaframma piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta (flap meat) la piemontese", "bavetta (flap meat) piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cubo per tagliata la piemontese", "cubo tagliata piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["polpa intera per tartare la piemontese", "polpa intera tartare piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["trita sceltissima la piemontese -", "trita sceltissima piemontese -"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fettine di carpaccio la piemontese", "fettine carpaccio piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["mix bollito di bovino la piemontese", "mix bollito bovino piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello pronto taglio la piemontese", "girello pronto taglio piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) di bovino argentina", "cuore costata (rib eye) bovino argentina"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto senza cordone 4/5 libbre di bovino argentina", "filetto senza cordone 4/5 libbre bovino argentina"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto senza cordone 3/4 libbre di bovino argentina", "filetto senza cordone 3/4 libbre bovino argentina"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino argentina", "controfiletto bovino argentina"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["tomahawk 7 coste di bovino canada heritage angus", "tomahawk 7 coste bovino canada heritage angus"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["t-bone 1 costa di bovino canada heritage angus", "t-bone 1 costa bovino canada heritage angus"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino canada heritage angus", "controfiletto bovino canada heritage angus"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto senza cordone di bovino canada heritage angus", "filetto senza cordone bovino canada heritage angus"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone a cuore di bovino canada heritage angus", "scamone cuore bovino canada heritage angus"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) di bovino adulto", "cuore costata (rib eye) bovino adulto"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di bovino adulto", "controfiletto bovino adulto"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto con cordone di bovino adulto", "filetto cordone bovino adulto"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lingua salmistrata (da cuocere) di bovino", "lingua salmistrata (da cuocere) bovino"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) di vitellone nazionale", "cuore costata (rib eye) vitellone nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di vitellone nazionale", "controfiletto vitellone nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto con cordone di vitellone nazionale", "filetto cordone vitellone nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombata disossata di vitellone nazionale", "lombata disossata vitellone nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo 3 coste vitellone nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["hamburger (200 g) la piemontese", "hamburger (200 g) piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["hamburger la piemontese", "hamburger piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["hamburger la piemontese -", "hamburger piemontese -"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["mini hamburger la piemontese", "mini hamburger piemontese"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["hamburger di bovino di razza chianina", "hamburger bovino razza chianina"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["mini hamburger di bovino di razza chianina", "mini hamburger bovino razza chianina"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["hamburger di bovino wagyu spagna", "hamburger bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["mini hamburger di bovino wagyu spagna", "mini hamburger bovino wagyu spagna"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["teste di filetto di vitello frisian", "teste filetto vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo 8 coste di vitello frisian", "lombo 8 coste vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["frenched rack 6 coste di vitello frisian", "frenched rack 6 coste vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["costoletta scalzata 6 coste di vitello frisian", "costoletta scalzata 6 coste vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di vitello frisian", "controfiletto vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto con cordone di vitello frisian", "filetto cordone vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone a cuore di vitello frisian", "scamone cuore vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello di vitello frisian", "girello vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["anchetta (spider steak) di vitello frisian", "anchetta (spider steak) vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fusello di vitello frisian", "fusello vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["stinco posteriore (spuntato) di vitello frisian", "stinco posteriore (spuntato) vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["guanciale di vitello frisian", "guanciale vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lingua di vitello frisian", "lingua vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["animelle di cuore di vitello frisian", "animelle cuore vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fegato di vitello frisian", "fegato vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cuore di vitello frisian", "cuore vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["rognone di vitello con grasso frisian", "rognone vitello grasso frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["coda di vitello frisian", "coda vitello frisian"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo 8 coste di vitello nazionale", "lombo 8 coste vitello nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto di vitello nazionale", "controfiletto vitello nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone a cuore di vitello nazionale", "scamone cuore vitello nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello di vitello nazionale", "girello vitello nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["copertina di spalla di vitello nazionale", "copertina spalla vitello nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["guanciale di vitello nazionale", "guanciale vitello nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["punta di petto senz'osso di vitello nazionale", "punta petto senz'osso vitello nazionale"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bresaola di manzo della valtellina igp", "bresaola manzo valtellina igp"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["carne salada di punta d'anca 2,5 kg", "carne salada punta d'anca 2,5 kg"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["controfiletto manzo america stagionato fumé"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello di manzo affumicato", "girello manzo affumicato"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bresaola di cavallo", "bresaola cavallo"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sfilacci di equino lavorati a mano", "sfilacci equino lavorati mano"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["petto vitello con osso", "petto vitello osso"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["pancia petto vitello disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["pancia vitello disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["petto vitello disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["reale vitello disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["reale vitellodisossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["spalla vitello disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["spalla vitellodisossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa vitello"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa vitello ita"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto vitello intero"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto vitello ita"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello vitello"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello vitello ita"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo vitello disossatos/v ita tfbf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo vitello extra disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo vitello macdisossatos/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombo vitello p/cost.con osso"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce vitello"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce vitello ita"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["polpa coscia vitello 4/t"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["polpa coscia vitello3/t"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone vitello"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone vitello ita"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sottofesa vitello c/gir."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima rare con osso", "lomb.b.a.carima rare osso"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima rare con osso crt", "lomb.b.a.carima rare osso crt"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima rare +"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima rare +crtf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima super.con osso crtf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima superior20kg+f"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima superior25kg+f"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima superior30kg+f"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima super25kg+crtf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lomb.b.a.carima uniqu25kg+crtf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombata b.a. con osso + marez.f", "lombata b.a. osso + marez.f"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombata b.a.con osso"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombata b.a.(galizia)con osso"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombata b.a.(galizia)c/ocrtx1f"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombata b.a.(galizia)ext.con osso"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombata b.a.con osso +"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["lombatacon osso"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta aloy.angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta aloy.bat.golds/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta aloyau angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta aloyau angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta flan.bat.golds/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta flanch.angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["bavetta flanch.angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["brisket b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cappello pret.angusgrainf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cappello prete angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cappello prete angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cappello prete b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cappello prete b.a.scozia igpf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cappello prete bat.gold"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["chuck eye b.a.wagyu"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["chuck flap b.a.wagyuf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["chuck roll b.a.wagyuf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["chuck roll b.a.t.golds/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["diaframma angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["diaframma angus scozia igps/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["diaframma b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa spalla angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa spalla angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa spalla angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa spalla b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa spalla bat.gold s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["flat iron steak b.a.scoziaigpf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello spalla angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["reale angus disossatos/v usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["reale angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["reale b.a.disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["reale cubetto angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["spalla b.a.disossatos/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["spencer roll b.a. carima"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["spencer roll b.a. scozia"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["spencer roll b.a.leg.s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["campanello b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll angus arg sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll b.a.wagyu"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll b.a.t.gold s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["cube roll b.a.scozia"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["entrecote bufalas/f"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa s/f angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa s/f b.a.t.gold"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa s/fascia angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filet mignon scam.b.a.svf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto angus 3/4lbs/varg sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto angus 4/5lbs/varg sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a. 3+kg"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a. lb"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.5lb+"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.6/7lb+"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.+1,,8kgsvf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.1,8-+svf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.2,,7kgs/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.2, kg s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.wagyus/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.4/5lb t.goldf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.s/cord.+s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto b.a.scozia +2,7kgf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto bufala"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["filetto ita vg"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello b.a. pad +"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello b.a. scozia"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["girello b.a.t.gold"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["muscolo b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["noce b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha g.fields i.s."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha angus arg sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha b.a. sashi"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha b.a.wagyu"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha b.a.t.gold"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha b.a.carima"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha b.a.scozia"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["picanha irl gf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["punta(picanha)b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef angus arg sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef angusgrain"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef b.a.grain s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef b.a.3/c"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef b.a.wagyuf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef b.a.t.golds/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef b.a.scozia s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["roast-beef bufala3/cs/v"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone angus arg sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone b.a. con punta", "scamone b.a. punta"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone cuore angus irl sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone cuore angusgrainf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone cuore b.a. scozia igpf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone cuore b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone cuore b.a.t.goldf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sottofesa angus aus sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sottofesa angus usa sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sottofesa angusgrain s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sottofesa b.a."], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sottofesa b.a.t.gold s/vf"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["sottofesa sq angus irl sm"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["testa filetto b.a.carima"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["carne per mac.vbac", "carne mac.vbac"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fesa vbac"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["fettine vbac"], sotto1: "Bovino", sotto2: "" },
  { keywords: ["scamone vbac ita"], sotto1: "Bovino", sotto2: "" },

  // ──────────────────────────────────────────────────
  // CONIGLIO
  // ──────────────────────────────────────────────────
  { keywords: ["coniglio di fattoria disossato ungheria", "coniglio fattoria disossato ungheria"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["sella disossata di coniglio di fattoria ungheria", "sella disossata coniglio fattoria ungheria"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["coscia disossata di coniglio di fattoria ungheria", "coscia disossata coniglio fattoria ungheria"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["coscia di coniglio nazionale", "coscia coniglio nazionale"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["coniglio disossato nazionale"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["sella di coniglio nazionale", "sella coniglio nazionale"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["filetto di coniglio nazionale", "filetto coniglio nazionale"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["fegatelli di coniglio", "fegatelli coniglio"], sotto1: "Coniglio", sotto2: "" },
  { keywords: ["rognoni di coniglio", "rognoni coniglio"], sotto1: "Coniglio", sotto2: "" },

  // ──────────────────────────────────────────────────
  // MAIALE
  // ──────────────────────────────────────────────────
  { keywords: ["sella di maialino da latte germania", "sella maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["pancia senz'osso stesa di maialino da latte germania", "pancia senz'osso stesa maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["coppa con cotenna di maialino da latte germania", "coppa cotenna maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["cosciotto con osso di maialino da latte germania", "cosciotto osso maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["cosciotto senza osso maialino da latte germania", "cosciotto senza osso maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["culatta senz'osso di maialino da latte germania", "culatta senz'osso maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["spalla con osso di maialino da latte germania", "spalla osso maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["spalla senza osso di maialino da latte germania", "spalla senza osso maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["stinco posteriore di maialino da latte germania", "stinco posteriore maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["guancia di maialino da latte germania", "guancia maialino latte germania"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["maialino da latte spagna", "maialino latte spagna"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["maialino da latte disossato spagna", "maialino latte disossato spagna"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["sella di maialino da latte spagna", "sella maialino latte spagna"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["frenched rack 10 coste di maialino da latte spagna", "frenched rack 10 coste maialino latte spagna"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["lonzetta senz'osso di maialino di latte spagna", "lonzetta senz'osso maialino latte spagna"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["pancia con osso di maialino da latte spagna", "pancia osso maialino latte spagna"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["coppa con cotenna di maialino da latte spagna", "coppa cotenna maialino latte spagna"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["carrè taglio bologna di suino nazionale", "carrè taglio bologna suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["lonza di suino nazionale", "lonza suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["filetto di suino nazionale", "filetto suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["costine taglio st. louis squadrate di suino nazionale", "costine taglio st. louis squadrate suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["costine del lombo taglio baby back di suino nazionale", "costine lombo taglio baby back suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["pancia squadrata con cotenna di suino nazionale", "pancia squadrata cotenna suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["stinco di suino nazionale", "stinco suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["rete di suino nazionale", "rete suino nazionale"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["conf. da", "conf."], sotto1: "Maiale", sotto2: "" },
  { keywords: ["lardo di maiale nero di parma podere cadassa", "lardo maiale nero parma podere cadassa"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["pancetta di maiale nero parmense - mezza", "pancetta maiale nero parmense - mezza"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["spalla cruda di palasone di maiale nero parmense", "spalla cruda palasone maiale nero parmense"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["sioka 56% cioccolato "ombré" costa d'avorio"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["tulakalum 75% cioccolato fondente belize"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["oqo 73% cioccolato fondente – blocco"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["araguani 72% cioccolato fondente venezuela"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["nyangbo 68% cioccolato fondente ghana"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["alpaco 66% cioccolato fondente ecuador"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["kalingo 65% cioccolato fondente grenada"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["manjari 64% cioccolato fondente madagascar"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["tainori 64% cioccolato fondente repubblica dominicana"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["illanka 63% cioccolato fondente perù"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["macaé 62% cioccolato fondente brasile"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["hukambi 53% cioccolato ombré brasile"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["bahibe 46% cioccolato al latte repubblica dominicana", "bahibe 46% cioccolato latte repubblica dominicana"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["amatika 46% cioccolato vegano"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["amatika blanche 35% cioccolato vegano"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["tanariva 33% cioccolato al latte madagascar", "tanariva 33% cioccolato latte madagascar"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["abinao 85% cioccolato fondente"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["guanaja 70% cioccolato fondente"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["caraibe 66 % cioccolato fondente"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["extra bitter 61% cioccolato fondente"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["jivara 40% cioccolato al latte", "jivara 40% cioccolato latte"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["3 kg pastiglie 34,70 al kg. 10%", "3 kg pastiglie 34,70 kg. 10%"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["3 kg pastiglie 34,80 al kg. 10%", "3 kg pastiglie 34,80 kg. 10%"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["millot 74% cioccolato fondente madagascar - bio"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["andoa 70% cioccolato fondente perù - bio"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["3 kg pastiglie 26,90 al kg. 10%", "3 kg pastiglie 26,90 kg. 10%"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["andoa 39% cioccolato al latte perù - bio", "andoa 39% cioccolato latte perù - bio"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["waina 35% cioccolato bianco e vaniglia bourbon - bio", "waina 35% cioccolato bianco vaniglia bourbon - bio"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["xocoline 65% cioccolato fondente"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["xocoline 41% cioccolato al latte", "xocoline 41% cioccolato latte"], sotto1: "Maiale", sotto2: "" },
  { keywords: ["dulcey 35% cioccolato biondo"], sotto1: "Maiale", sotto2: "" },

  // ──────────────────────────────────────────────────
  // POLLO
  // ──────────────────────────────────────────────────
  { keywords: ["pollo di bresse dop", "pollo bresse dop"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["cappone nostrano di cascina", "cappone nostrano cascina"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["cappone disossato (disponibilità dicembre)"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["pollo nostrano a busto", "pollo nostrano busto"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["pollastra nostrana a busto", "pollastra nostrana busto"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["gallina ruspante a busto nazionale", "gallina ruspante busto nazionale"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["gallina media a busto nazionale", "gallina media busto nazionale"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["tacchina a busto nazionale", "tacchina busto nazionale"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["galletto disossato nazionale"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["galletto a busto nazionale", "galletto busto nazionale"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["galletto di borgogna a busto", "galletto borgogna busto"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["gallo giovane di cascina", "gallo giovane cascina"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto con ala di galletto nazionale", "petto ala galletto nazionale"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["galletto cotto erb400gs/vcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto pollo mar.prec. t/r"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["rollata classica amadori"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["rollata classica amadori 700gf"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["arrotolato fesa tacc.cl.a tr"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["cappone abfconf. cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["cappone testa zampe confx1claf"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["coscia anatra x 2 cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["coscia pollo x10 s/vhalalcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["coscia pollo x10 180/220gcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["coscia pollo 240/280gcl.a mf"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["coscia pollo 255/295gs/v cl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["coscia pollos/p disossatocl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["cuori pollo film cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["faraonaparz.disossatos/v cl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fegato grasso anatra extra"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fegato grasso oca extra"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fegato pollocl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fesa tacc.femm. cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fesa tacc.fette cl.a tr"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fesa taccfette cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fesa tacchino abf cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fesa tacchino cuore cl.a mf"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fesa tacchino halal cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fesa tacchino cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fuso pollo x10 145/175gs/vclaf"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fuso pollo x8 170/200gs/vcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["fuso pollo cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["galletto busto conf.x 1 cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["galletto vallespl450-530gcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["involtini pollo"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["lombo conigliofilm"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto anatra 700/ s/vcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto faraona c/ali film cl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto faraona x 2 film cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto faraona cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto polfette cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto pollo c/ala s/vcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto pollo halal x5 filmcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["petto pollo cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["salsiccia pol/sui/tac."], sotto1: "Pollo", sotto2: "" },
  { keywords: ["salsiccia pol/tac/sui1kgf"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["salsiccia pollo halal"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["salsiccia pollo tacchino"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["salsiccia pollo/suin780gf"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["salsiccia tacchino/suinof"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["sovrac.pollo senza osso cl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["sovrac.pollocon osso cl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["sovrac.pollox10 s/vcl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["sovrac.tacch.senza osso cl.af"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["spezzatino pollo cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["spezzatino tacchino cl.a"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["spiedini bonta' filzate"], sotto1: "Pollo", sotto2: "" },
  { keywords: ["spiedini fantasia fam."], sotto1: "Pollo", sotto2: "" },
  { keywords: ["spiedini tacchino halal"], sotto1: "Pollo", sotto2: "" },

  // ──────────────────────────────────────────────────
  // SELVAGGINA
  // ──────────────────────────────────────────────────
  { keywords: ["faraona di cascina a busto", "faraona cascina busto"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["petto (senza ala, con pelle) di faraona di cascina", "petto (senza ala, pelle) faraona cascina"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia di faraona di cascina", "coscia faraona cascina"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["faraona disossata nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["petto (senza ala) di faraona nazionale", "petto (senza ala) faraona nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["suprema (mezzo petto con ala) di faraona nazionale", "suprema (mezzo petto ala) faraona nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["suprema (mezzo petto con ala) di faraona francia", "suprema (mezzo petto ala) faraona francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia di faraona nazionale", "coscia faraona nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["piccione spiumato a mano nazionale", "piccione spiumato mano nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["piccione spiumato a mano francia", "piccione spiumato mano francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["piccione d'anjou spiumato a mano", "piccione d'anjou spiumato mano"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["piccione imperiale francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["piccione disossato francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["suprema (mezzo petto con ala) di piccione francia", "suprema (mezzo petto ala) piccione francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscetta di piccione francia", "coscetta piccione francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["quaglia gigante francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["quaglia gigante nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["quaglia gigante disossata francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["quaglia gigante disossata nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["petto di quaglia (senza ala e senza pelle) nazionale", "petto quaglia (senza ala senza pelle) nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["suprema (mezzo petto con ala) di quaglia francia", "suprema (mezzo petto ala) quaglia francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscetta di quaglia nazionale", "coscetta quaglia nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["uova di quaglia fresche francia", "uova quaglia fresche francia"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["uova di quaglia fresche nazionali", "uova quaglia fresche nazionali"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["cuore di costata (rib eye) di bisonte", "cuore costata (rib eye) bisonte"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["controfiletto di bisonte", "controfiletto bisonte"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["scamone a cuore di bisonte", "scamone cuore bisonte"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["filetto con cordone di equino", "filetto cordone equino"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["controfiletto di equino", "controfiletto equino"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["polpa di coscia equino", "polpa coscia equino"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["sella tagliata a metà di cervo cacciato ungheria", "sella tagliata metà cervo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["controfiletto di cervo cacciato ungheria", "controfiletto cervo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["filetto di cervo cacciato ungheria", "filetto cervo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["costine di cervo cacciato ungheria", "costine cervo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia con osso di cervo cacciato ungheria", "coscia osso cervo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["spalla disossata di cervo cacciato ungheria", "spalla disossata cervo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bocconcini di cervo cacciato ungheria", "bocconcini cervo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["sella di capriolo cacciato spagna", "sella capriolo cacciato spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["controfiletto di capriolo cacciato ungheria", "controfiletto capriolo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["spalla disossata di capriolo cacciato ungheria", "spalla disossata capriolo cacciato ungheria"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["filetto di cinghiale nazionale", "filetto cinghiale nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia disossata di cinghiale nazionale", "coscia disossata cinghiale nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["sella di cinghiale nazionale", "sella cinghiale nazionale"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["sella di cinghiale cacciato spagna", "sella cinghiale cacciato spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["frenched rack 10 coste di cinghiale cacciato spagna", "frenched rack 10 coste cinghiale cacciato spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["sella di marcassin (cinghialetto) cacciato spagna", "sella marcassin (cinghialetto) cacciato spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia 4 tagli marcassin spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coniglio selvatico senza testa cacciato spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["pernice rossa senza testa cacciata spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["colombaccio senza testa spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["germano senza testa cacciato spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["fagiano senza testa cacciato spagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["torchon di fegato grasso d'oca intero rougiè", "torchon fegato grasso d'oca intero rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["fegato grasso d'anatra intero in vasetto di vetro rougiè", "fegato grasso d'anatra intero vasetto vetro rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di fegato grasso d'oca intero rougiè", "terrina fegato grasso d'oca intero rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di fegato grasso d'anatra intero rougiè", "terrina fegato grasso d'anatra intero rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["180 g vaschetta con astuccio 24,80 cad.", "180 g vaschetta astuccio 24,80 cad."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["500 g vaschetta con astuccio 67,10 cad.", "500 g vaschetta astuccio 67,10 cad."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di fegato grasso d'anatra intero ai fichi rougiè", "terrina fegato grasso d'anatra intero ai fichi rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrine da", "terrine"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["assortimento 12 terrine di fegato grasso rougiè", "assortimento 12 terrine fegato grasso rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["monoporzione di fegato grasso d'anatra intero rougiè", "monoporzione fegato grasso d'anatra intero rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bloc di fegato grasso d'oca con pezzi rougiè", "bloc fegato grasso d'oca pezzi rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bloc di fegato grasso d'anatra con pezzi rougiè", "bloc fegato grasso d'anatra pezzi rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bloc di fegato grasso d'oca "allegro" rougiè", "bloc fegato grasso d'oca "allegro" rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bloc di fegato grasso d'anatra "allegro" rougiè", "bloc fegato grasso d'anatra "allegro" rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["monoporzione di bloc di fegato grasso d'oca rougiè", "monoporzione bloc fegato grasso d'oca rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["monoporzione di bloc di fegato grasso d'anatra rougiè", "monoporzione bloc fegato grasso d'anatra rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["grasso fuso raffinato d'anatra rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["grasso fuso raffinato d'oca"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["grasso d'oca in vasetto", "grasso d'oca vasetto"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["pate' di fegato grasso d'oca rougiè", "pate' fegato grasso d'oca rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["500 g sacchetto s/v 21,90 cad."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["mousse di fegato grasso d'oca rougiè", "mousse fegato grasso d'oca rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["mousse di fegato grasso d'anatra rougiè", "mousse fegato grasso d'anatra rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["500 g vaschetta 19,10 cad."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di piccione e fegato grasso d'anatra rougiè", "terrina piccione fegato grasso d'anatra rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di fagiano ai funghi cantarelli rougiè", "terrina fagiano ai funghi cantarelli rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di carne d'anatra all'arancia rougiè", "terrina carne d'anatra all'arancia rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di fegatelli rougiè", "terrina fegatelli rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["cofanetto "la collection" rougiè 3 x"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["180 g vasetto vetro 34,60 cad."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["200 g scatola 31,90 cad."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["145 g scatola 18,80 cad."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bloc di fegato grasso d'oca rougiè", "bloc fegato grasso d'oca rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bloc di fegato grasso d'anatra rougiè", "bloc fegato grasso d'anatra rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["bloc di fegato grasso d'oca tartufato rougiè", "bloc fegato grasso d'oca tartufato rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: [""duo" bloc di fegato grasso d'oca e d'anatra rougiè", ""duo" bloc fegato grasso d'oca d'anatra rougiè"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["terrina di faraona ai pistacchi", "terrina faraona ai pistacchi"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia di anatra in confit", "coscia anatra confit"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia di anatra in confit -", "coscia anatra confit -"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["alette di anatra in confit", "alette anatra confit"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["sfilacci d'anatra in confit", "sfilacci d'anatra confit"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["coscia di faraona disossata e farcita", "coscia faraona disossata farcita"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["quaglia disossata e farcita", "quaglia disossata farcita"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica belon du belon® "5 / p" pz. 100 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica belon du belon® "1 / g" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica belon du belon® "00 / tg" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica belon du belon® "00 / tg" pz.24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica belon du belon® "000 / ttg" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica belon du belon® "000 / ttg" pz. 25 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica belon du belon® "0000 / hc" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "1" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "2" pz. 96 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "2" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "2" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "2" pz.12 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "3" pz. 100 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "3" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "3" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine binic selvaggia "3" pz.12 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "1" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "2" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "2" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "2" pz.12 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "3" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "3" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "3" pz. 12 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica perle noire "4" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tsaritsa® "1" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tsaritsa® "2" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tsaritsa® "3" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tsaritsa® "4" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine di bretagna standard "3" cadoret", "ostrica fine bretagna standard "3" cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine di bretagna standard "4" cadoret", "ostrica fine bretagna standard "4" cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale di carantec "1" pz. 50 cadoret", "ostrica speciale carantec "1" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale di carantec "2" pz. 50 cadoret", "ostrica speciale carantec "2" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale di carantec "2" pz. 24 cadoret", "ostrica speciale carantec "2" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale di carantec "3" pz. 50 cadoret", "ostrica speciale carantec "3" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale di carantec "3" pz. 24 cadoret", "ostrica speciale carantec "3" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine tipo saint-vaast "2" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica fine tipo saint-vaast "3" pz. 24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale tipo isigny "2" pz. 48 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale tipo isigny "3" pz. 50 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale tipo isigny "3" pz.24 cadoret"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica super speciale utah beach "1" hamel & fils"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica super speciale utah beach "2" hamel & fils"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica super speciale utah beach "3" hamel &amp; fils"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale de claire ancelin "2" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale de claire ancelin "3" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale de claire ancelin "4" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale de claire ancelin "5" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale gillardeau "0" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale gillardeau "1" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale gillardeau "2" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale gillardeau "3+" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale gillardeau "3" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica speciale gillardeau "4" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica "riserva" del gargano "1"", "ostrica "riserva" gargano "1""], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica del gargano "2"", "ostrica gargano "2""], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica del gargano "3"", "ostrica gargano "3""], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica del gargano "4"", "ostrica gargano "4""], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tia maraa "1" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tia maraa "2" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tia maraa "3" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica tia maraa "4" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica josephine "1" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica josephine "2" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica josephine "3" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["ostrica josephine "4" pz."], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["cozza dell'adriatico (disponibilità mag- set)"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["cozza di palo francese (bouchot)", "cozza palo francese (bouchot)"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["vongole extra dell' adriatico"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["vongole grandi dell'adriatico"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["vongole veraci "medie" della bretagna", "vongole veraci "medie" bretagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["vongole veraci "grandi" della bretagna", "vongole veraci "grandi" bretagna"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["tartufo o noce di mare", "tartufo noce mare"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["fasolaro"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["cappasanta americana"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["cappasanta atlantica polpa con corallo", "cappasanta atlantica polpa corallo"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["cappasanta atlantica mezzo guscio"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["riccio di mare dell’adriatico", "riccio mare dell’adriatico"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["gusci di riccio di mare ø 4 cm", "gusci riccio mare ø 4 cm"], sotto1: "Selvaggina", sotto2: "" },
  { keywords: ["gusci di riccio di mare ø 5 cm", "gusci riccio mare ø 5 cm"], sotto1: "Selvaggina", sotto2: "" },
]